version: '3'

services:
  postgres:
    container_name: lundegaard
    image: library/postgres:13.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=lundegaard