spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:1331/lundegaard
    username: test
    password: test
  application:
    name: lundegaard
