spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/lundegaard
    username: test
    password: test
  application:
    name: lundegaard
