create table contact_form_entity
(
    id              int8 generated by default as identity,
    created_at      timestamp,
    modified_at     timestamp,
    name            varchar(255),
    policy_number   varchar(255),
    request_message varchar(255),
    surname         varchar(255),
    request_type_id int8,
    primary key (id)
);
create table request_type_entity
(
    id                int8 generated by default as identity,
    created_at        timestamp,
    modified_at       timestamp,
    request_type_name varchar(255),
    primary key (id)
);
alter table if exists request_type_entity
    drop constraint if exists UK_t1urhanqgjryacc9ofjfxyx49;
alter table if exists request_type_entity
    add constraint UK_t1urhanqgjryacc9ofjfxyx49 unique (request_type_name);
alter table if exists contact_form_entity
    add constraint FKkb372ke66q6uo0uidpqejj68 foreign key (request_type_id) references request_type_entity;