create table contact_form_entity
(
    id              int8 generated by default as identity,
    created_at      timestamp,
    modified_at     timestamp,
    name            varchar(255),
    policy_number   varchar(255),
    request_message varchar(255),
    surname         varchar(255),
    request_type_id int8,
    primary key (id)
);
create table request_type_entity
(
    id                int8 generated by default as identity,
    created_at        timestamp,
    modified_at       timestamp,
    request_type_name varchar(255),
    primary key (id)
);
alter table if exists request_type_entity
    drop constraint if exists UQ_request_type_entity_name;
alter table if exists request_type_entity
    add constraint UQ_request_type_entity_name unique (request_type_name);
alter table if exists contact_form_entity
    add constraint FK_contract_form_entity_request_type foreign key (request_type_id) references request_type_entity;